

describe('Account.isValidAddress', function() {

  it("returns true for valid address", function() {
    var addresses = [
      'GAV4RUTR7VDXTBM7HACQBEDD6Y5CHJVYWFIGPCYEKKSS6TRDYIAPHUYV',
      'GB6SUQC3XV2IFJZ5EJ2MFVJCR2KYIW3HL33KVWGR2GII5LMEZDN2XLSE',
      'GAYOKHCIKPJ42R6WWVIIMNWI6UYSMYNSUXTXHOKQ24H44HY65TDGBET7',
      'GAL3IJMPFBFFBI4D3LD3GY6BDMQICQQUD3DEOM7D3MYOBORP3M45ISHD',
      'GDXIIZTKTLVYCBHURXL2UPMTYXOVNI7BRAEFQCP6EZCY4JLKY4VKFNLL',
      'GB73HMHUZV6FZ4ZG5U7VKRPEVH5DMT3FLL2MUGGXKS6KNLKXPCSR25KX',
      'GB56XD7IV5MXTCZ6VJ5KA2VZEAW3XXD6A5KEPSU7KQH65BJHXRZGU6KX',
      'GDWRFGM5ZPNVOMWOCCVAWF42QZNHOIWSXEFR2VHLOKKMPBLQISL6WVYV',
      'GD2ZWEDUARNC5CEDV3WULG3FCRFNTCJJUCZHYUDWN4VAXJCHFQ4JZOVC',
      'GCM2DX5J4O6QKTLYBMZXO3I4F34RMJ3JEGBIGRGZG5WZ4KSUUTVKYKBL',
      'GCMYUI4DOJ2PK2DU4B55BUAV2TF5CAFJHHP626OEJNUCY3WJS24XSORK',
      'GA37WJKIEMPSC7SCFD76Y464OJW5J6SQW2QBKKT7BJXA4WEIEWCXAG46',
      'GCDYJTVADM6T354W7X3J27GQOOOLRIOXF5EAGIGHKVRKKCZKAEK56GPQ'
    ];

    for (var i in addresses) {
      expect(StellarBase.Account.isValidAddress(addresses[i])).to.be.true;
    }
  });

  it("returns false for invalid address", function() {
    var addresses = [
      'GDXIIZTKTLVYCBHURXL2UPMTYXOVNI7BRAEFQCP6EZCY4JLKY4VKFNLT',
      'gWRYUerEKuz53tstxEuR3NCkiQDcV4wzFHmvLnZmj7PUqxW2wt',
      'test',
      'g4VPBPrHZkfE8CsjuG2S4yBQNd455UWmk' // Old network address
    ];

    for (var i in addresses) {
      expect(StellarBase.Account.isValidAddress(addresses[i])).to.be.false;
    }
  });

});
